server:
  port: 8085

spring:
  application:
    name: employee-service

  # --- Database Configuration ---
  datasource:
    url: jdbc:mysql://localhost:7294/jso_payroll_db?createDatabaseIfNotExist=true
    username: root
    password: Jusp.020794
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- JPA / Hibernate Configuration ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Professional standard for MySQL 8+ and Hibernate 6+
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # --- Security Configuration ---
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: "classpath:public.pem"

# --- NEW: Service Discovery Link ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE